package codeaudit

import (
	"bufio"
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// ── Audit Report Types ────────────────────────────────────

// AuditReport is the comprehensive security audit result for a code directory.
type AuditReport struct {
	ReportID     string          `json:"report_id"`
	AuditTime    string          `json:"audit_time"`
	Target       AuditTarget     `json:"target"`
	Conclusion   AuditConclusion `json:"conclusion"`
	Statistics   AuditStatistics `json:"statistics"`
	FileReports  []FileReport    `json:"file_reports"`
	ScanMetadata AuditMetadata   `json:"scan_metadata"`
}

// AuditTarget describes what was audited.
type AuditTarget struct {
	Directory         string `json:"directory"`
	FilesScanned      int    `json:"files_scanned"`
	TotalLines        int    `json:"total_lines"`
	FilesWithFindings int    `json:"files_with_findings"`
}

// AuditConclusion is the final audit verdict.
type AuditConclusion struct {
	Passed         bool   `json:"passed"`
	RiskLevel      string `json:"risk_level"` // CRITICAL / HIGH / MEDIUM / LOW / NONE
	Summary        string `json:"summary"`
	Recommendation string `json:"recommendation"`
	Statistics     AuditStatistics `json:"statistics"`
}

// AuditStatistics holds aggregated finding counts.
type AuditStatistics struct {
	TotalFindings int `json:"total_findings"`
	High          int `json:"high"`
	Medium        int `json:"medium"`
	Malicious     int `json:"malicious"`
	Suspicious    int `json:"suspicious"`
	Benign        int `json:"benign"`
	Uncertain     int `json:"uncertain"`
}

// FileReport is the analysis result for a single source file.
type FileReport struct {
	File                   string    `json:"file"`
	FilePath               string    `json:"file_path"`
	FindingsCount         int       `json:"findings_count"`
	HighCount             int       `json:"high_count"`
	MediumCount           int       `json:"medium_count"`
	RiskLevel             string    `json:"risk_level"`  // LLM or inferred
	Summary               string    `json:"summary"`     // LLM or inferred
	HasExfiltrationPattern bool     `json:"has_exfiltration_pattern"` // LLM
	Chained               bool      `json:"chained"`     // LLM
	Findings              []Finding `json:"findings"`
}

// AuditMetadata records scan configuration and timing.
type AuditMetadata struct {
	ScannerVersion string `json:"scanner_version"`
	RulesCount     int    `json:"rules_count"`
	LLMModel       string `json:"llm_model"`
	LLMEnabled     bool   `json:"llm_enabled"`
	Policy         string `json:"policy"`
	ScanDurationMs int64  `json:"scan_duration_ms"`
}

// FileSummary is the LLM response for file-level analysis.
type FileSummary struct {
	RiskLevel    string `json:"risk_level"`
	Summary      string `json:"summary"`
	Chained      bool   `json:"chained"`
	Exfiltration bool   `json:"exfiltration"`
}

// ── Rule suggestion map ───────────────────────────────────

// ruleSuggestionMap provides fix suggestions keyed by rule ID.
// Hardcoded in Go (not generated by LLM) for reliability.
var ruleSuggestionMap = map[string]string{
	"NET_001": "移除网络请求，或限制为仅发送模型指标",
	"NET_002": "移除原始 Socket 连接",
	"CMD_001": "移除子进程调用，使用安全的替代方案",
	"OBF_001": "移除编码/反序列化操作，使用安全的替代方案",
	"DYN_001": "移除 eval/exec，使用安全的替代方案",
	"FIL_001": "移除敏感文件读取",
	"ENV_001": "使用配置文件替代环境变量读取",
	"PER_001": "移除持久化机制",
	"EXF_001": "移除数据编码和发送操作",
	"EMB_001": "不要将原始数据写入输出文件",
	"EMB_002": "不要将数据复制到输出目录",
	"EMB_003": "避免在日志中打印原始数据",
	"EMB_004": "不要将数据编码后嵌入模型权重",
}

// SuggestionForRule returns the fix suggestion for a given rule ID.
func SuggestionForRule(ruleID string) string {
	if s, ok := ruleSuggestionMap[ruleID]; ok {
		return s
	}
	return "审查该代码片段并确认其安全性"
}

// ── Core aggregation functions ────────────────────────────

// GroupFindingsByFile groups findings by their file path.
func GroupFindingsByFile(findings []Finding) map[string][]Finding {
	groups := make(map[string][]Finding)
	for _, f := range findings {
		groups[f.File] = append(groups[f.File], f)
	}
	return groups
}

// BuildFileReport constructs a FileReport from findings (Go-computed fields only).
// LLM fields (RiskLevel, Summary, Chained, HasExfiltrationPattern) are left empty
// and should be filled by analyzeFileWithLLM.
func BuildFileReport(filePath string, findings []Finding) FileReport {
	highCount := 0
	mediumCount := 0
	for _, f := range findings {
		switch f.Severity {
		case SeverityHigh:
			highCount++
		case SeverityMedium:
			mediumCount++
		}
	}

	fr := FileReport{
		File:            filepath.Base(filePath),
		FilePath:        filePath,
		FindingsCount:  len(findings),
		HighCount:      highCount,
		MediumCount:    mediumCount,
		Findings:       findings,
	}

	// If no LLM, infer risk level from static data.
	fr.RiskLevel = InferRiskLevel(highCount, mediumCount)
	fr.Summary = "仅静态扫描，未进行语义分析"

	return fr
}

// InferRiskLevel determines risk level from static finding counts.
func InferRiskLevel(highCount, mediumCount int) string {
	if highCount > 0 {
		return "HIGH"
	}
	if mediumCount > 0 {
		return "MEDIUM"
	}
	return "LOW"
}

// ComputeStatistics aggregates finding counts.
func ComputeStatistics(findings []Finding) AuditStatistics {
	stats := AuditStatistics{
		TotalFindings: len(findings),
	}
	for _, f := range findings {
		switch f.Severity {
		case SeverityHigh:
			stats.High++
		case SeverityMedium:
			stats.Medium++
		}
		switch f.LLMVerdict {
		case "MALICIOUS":
			stats.Malicious++
		case "SUSPICIOUS":
			stats.Suspicious++
		case "BENIGN":
			stats.Benign++
		case "UNCERTAIN":
			stats.Uncertain++
		}
	}
	return stats
}

// ComputeConclusion determines the audit conclusion from statistics and policy.
func ComputeConclusion(stats AuditStatistics, fileReports []FileReport, policy string) AuditConclusion {
	riskLevel := "NONE"

	if stats.Malicious > 0 {
		riskLevel = "CRITICAL"
	} else if stats.High > 0 && stats.Suspicious > 0 {
		riskLevel = "HIGH"
	} else if stats.High > 0 {
		// HIGH findings exist but LLM judged them BENIGN
		riskLevel = "MEDIUM"
	} else if stats.Medium > 0 {
		riskLevel = "LOW"
	}

	// Pass/fail depends on policy.
	hasLLMVerdict := stats.Malicious > 0 || stats.Suspicious > 0 || stats.Benign > 0 || stats.Uncertain > 0
	var passed bool
	switch policy {
	case "gate":
		// Gate mode: block on MALICIOUS/SUSPICIOUS, and also block on raw static
		// findings when no LLM verdict is available to downgrade them.
		passed = stats.Malicious == 0 && stats.Suspicious == 0
		if passed && !hasLLMVerdict && (stats.High > 0 || stats.Medium > 0) {
			passed = false
			if stats.High > 0 {
				riskLevel = "HIGH"
			} else {
				riskLevel = "MEDIUM"
			}
		}
	default:
		// Assist mode (default): preserve the static scan decision.
		// Any HIGH finding still blocks, even if LLM is absent or says BENIGN.
		passed = stats.Malicious == 0 && stats.High == 0
	}

	summary := buildSummaryText(stats, riskLevel)
	recommendation := buildRecommendation(fileReports)

	return AuditConclusion{
		Passed:         passed,
		RiskLevel:      riskLevel,
		Summary:        summary,
		Recommendation: recommendation,
		Statistics:      stats,
	}
}

// ── Report assembly ───────────────────────────────────────

// AssembleAuditReport combines all components into the final AuditReport.
func AssembleAuditReport(
	dir string,
	scanReport *Report,
	fileReports []FileReport,
	fileLineCounts map[string]int,
	cfg LLMConfig,
	duration time.Duration,
) *AuditReport {
	stats := ComputeStatistics(scanReport.Findings)

	// Sort file reports: HIGH risk first, then by findings count.
	sort.Slice(fileReports, func(i, j int) bool {
		ri, rj := riskOrder(fileReports[i].RiskLevel), riskOrder(fileReports[j].RiskLevel)
		if ri != rj {
			return ri < rj // lower order = higher risk, comes first
		}
		return fileReports[i].FindingsCount > fileReports[j].FindingsCount
	})

	conclusion := ComputeConclusion(stats, fileReports, cfg.Policy)

	totalLines := 0
	for _, count := range fileLineCounts {
		totalLines += count
	}

	return &AuditReport{
		ReportID:  GenerateReportID(),
		AuditTime: time.Now().Format(time.RFC3339),
		Target: AuditTarget{
			Directory:         dir,
			FilesScanned:      scanReport.FilesCount,
			TotalLines:        totalLines,
			FilesWithFindings: len(fileReports),
		},
		Conclusion: conclusion,
		Statistics: stats,
		FileReports: fileReports,
		ScanMetadata: AuditMetadata{
			ScannerVersion: "1.0.0",
			RulesCount:     len(DefaultRules()),
			LLMModel:       cfg.Model,
			LLMEnabled:     cfg.Enabled,
			Policy:         cfg.Policy,
			ScanDurationMs: duration.Milliseconds(),
		},
	}
}

// ── Helper functions ──────────────────────────────────────

// GenerateReportID creates a unique audit report identifier.
func GenerateReportID() string {
	ts := time.Now().Format("20060102-150405")
	b := make([]byte, 4)
	_, _ = rand.Read(b)
	return fmt.Sprintf("audit-%s-%x", ts, b)
}

// BuildFindingsSummary creates a compact summary of findings for the LLM prompt.
// e.g. "NET_001(网络请求,HIGH), CMD_001(命令执行,HIGH)"
func BuildFindingsSummary(findings []Finding) string {
	if len(findings) == 0 {
		return "无"
	}
	parts := make([]string, 0, len(findings))
	seen := make(map[string]bool)
	for _, f := range findings {
		key := f.RuleID
		if seen[key] {
			continue
		}
		seen[key] = true
		parts = append(parts, fmt.Sprintf("%s(%s,%s)", f.RuleID, f.Category, f.Severity))
	}
	return strings.Join(parts, ", ")
}

// ReadFileForAnalysis reads a source file and returns up to maxLines lines.
func ReadFileForAnalysis(path string, maxLines int) string {
	f, err := os.Open(path)
	if err != nil {
		return "// 无法读取文件"
	}
	defer f.Close()

	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() && len(lines) < maxLines {
		lines = append(lines, scanner.Text())
	}

	if len(lines) == 0 {
		return "// 文件为空"
	}

	code := strings.Join(lines, "\n")
	if scanner.Scan() {
		// More lines exist — add truncation notice.
		code += fmt.Sprintf("\n// ... (截断，文件超过 %d 行)", maxLines)
	}
	return code
}

// CountFileLines returns the number of lines in a file.
func CountFileLines(path string) int {
	f, err := os.Open(path)
	if err != nil {
		return 0
	}
	defer f.Close()

	count := 0
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		count++
	}
	return count
}

// ── Internal helpers ──────────────────────────────────────

func buildSummaryText(stats AuditStatistics, riskLevel string) string {
	if stats.TotalFindings == 0 {
		return "未发现安全问题，代码通过审计"
	}

	parts := []string{}
	if stats.Malicious > 0 {
		parts = append(parts, fmt.Sprintf("发现 %d 处恶意代码", stats.Malicious))
	}
	if stats.Suspicious > 0 {
		parts = append(parts, fmt.Sprintf("发现 %d 处可疑代码", stats.Suspicious))
	}
	if stats.Benign > 0 && len(parts) > 0 {
		parts = append(parts, fmt.Sprintf("%d 处已确认为正常", stats.Benign))
	}

	if len(parts) == 0 {
		return fmt.Sprintf("发现 %d 处安全问题（静态扫描），未经语义分析", stats.TotalFindings)
	}

	summary := "审计结论: " + strings.Join(parts, "，")

	if riskLevel == "CRITICAL" {
		summary += "。存在数据泄露风险，建议阻断导入"
	}
	return summary
}

func buildRecommendation(fileReports []FileReport) string {
	// Collect unique rule IDs from malicious/suspicious findings.
	ruleIDs := make(map[string]bool)
	for _, fr := range fileReports {
		for _, f := range fr.Findings {
			if f.LLMVerdict == "MALICIOUS" || f.LLMVerdict == "SUSPICIOUS" {
				ruleIDs[f.RuleID] = true
			}
		}
	}

	if len(ruleIDs) == 0 {
		// Check for unresolved HIGH findings.
		for _, fr := range fileReports {
			for _, f := range fr.Findings {
				if f.Severity == SeverityHigh && f.LLMVerdict == "" {
					ruleIDs[f.RuleID] = true
				}
			}
		}
	}

	if len(ruleIDs) == 0 {
		return "无需修复"
	}

	var suggestions []string
	for ruleID := range ruleIDs {
		s := SuggestionForRule(ruleID)
		suggestions = append(suggestions, fmt.Sprintf("%s: %s", ruleID, s))
	}
	sort.Strings(suggestions)

	return "建议修复: " + strings.Join(suggestions, "; ")
}

func riskOrder(level string) int {
	switch level {
	case "CRITICAL":
		return 0
	case "HIGH":
		return 1
	case "MEDIUM":
		return 2
	case "LOW":
		return 3
	case "NONE":
		return 4
	default:
		return 5
	}
}
